### ISSUE TITLE
CAN-FIX plugin crashes with bad CAN messages

### ISSUE THREAD

**Issue by birkelbach** [makerplane/FIX-Gateway#76] opened 2019-07-19 02:12 UTC
The 'canfix' plugin is crashing when the python-canfix module raises exceptions for bad messages that it received on the CAN Bus.  All of these exceptions need to be caught and the plugin continue operating no matter what.

**Comment by birkelbach** [comment] 2019-08-07 14:33
I'm having trouble duplicating this behaviour.  Tests that send random data to all CAN IDs and all data lengths don't cause the module to crash.  It may have been fixed with the filtering since the offending frames may not be getting into the python-canfix module in the first place.

**Comment by e100** [comment] 2024-05-14 23:11
I've not been able to reproduce this and much has changed in the CAN code since this issue was opened.

Closing this, please re-open should the issue resurface.

**Closed** 2024-05-14 23:11 UTC
Labels: bug
